- hosts: main
  sudo: yes
  tasks:

    - apt: update_cache=yes
    - name: install libs
      apt: name={{item}} state=installed
      with_items:
        - git

        - gcc
        - g++
        - llvm-3.6-dev
        - libedit-dev

        - python3-pip
        - cython3

    - shell: pip3 install --upgrade pip

    - pip: name={{item}} executable=/usr/local/bin/pip3
      environment:
        LLVM_CONFIG: '/usr/bin/llvm-config-3.6'
      with_items:
        - numpy
        - pandas
        - matplotlib
        - Pillow
        - jupyter
        - sympy
        - llvmlite==0.8.0
        - numba==0.23.1
        - scipy
        - scikit-learn
        - tensorflow

    - shell: hostname {{hostname}}
    - template: src=templates/hosts dest=/etc/hosts
    - template: src=templates/hostname dest=/etc/hostname

    - shell: echo "cd ~/data/" > .bash_profile
      sudo: no

